version: '3.3'

networks:
  mvc:

services:
  nginx:
    image: nginx:stable
    container_name: mvc_nginx
    ports:
      - "62:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mvc

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: mvc_php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - mvc

  mysql:
    image: mysql:8.0
    container_name: mvc_mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mvc
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - mvc

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: mvc_phpmyadmin
      restart: always
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_PORT=3306
      ports:
        - 127.0.0.1:84:80
      volumes:
        - /sessions
      links:
        - mysql
      networks:
        - mvc

